// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseCodeProject() {
  return window['go']['main']['App']['CloseCodeProject']();
}

export function GetAvailableModels() {
  return window['go']['main']['App']['GetAvailableModels']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function HideToTray() {
  return window['go']['main']['App']['HideToTray']();
}

export function SelectCodeProject() {
  return window['go']['main']['App']['SelectCodeProject']();
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}
