// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseCodeProject():Promise<void>;

export function GetAvailableModels():Promise<Array<Record<string, any>>>;

export function GetVersion():Promise<string>;

export function HideToTray():Promise<void>;

export function SelectCodeProject():Promise<Record<string, string>>;

export function SelectDirectory():Promise<string>;

export function ShowWindow():Promise<void>;
