// STATUS: PLATIN
// Local UI projection of the Go Intelligence Core. All variable content uses textContent.
let selectedCaseId = null;
let animationFrame = 0;
let intelligenceStream = null;
let globeRotation = 0;
let globeZoom = 1;
let globeControlsBound = false;
let briefingBound = false;
const endpoint = '/v1/intelligence/';

async function request(path, options = {}) { const response = await fetch(endpoint + path, { headers: {'Content-Type':'application/json'}, ...options }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error || 'Intelligence request failed'); return payload; }
function text(el, value) { el.textContent = value || ''; return el; }
function row(title, meta, status) { const item=document.createElement('button'); item.type='button'; item.className='intel-row'; const strong=document.createElement('strong'); text(strong,title); const small=document.createElement('small'); text(small,meta); const badge=document.createElement('span'); text(badge,status); item.append(strong,small,badge); return item; }
function bindGlobeControls(canvas){if(globeControlsBound)return;globeControlsBound=true;let dragging=false,lastX=0;canvas.addEventListener('pointerdown',event=>{dragging=true;lastX=event.clientX;canvas.setPointerCapture(event.pointerId)});canvas.addEventListener('pointermove',event=>{if(!dragging)return;globeRotation+=(event.clientX-lastX)*.35;lastX=event.clientX});canvas.addEventListener('pointerup',()=>{dragging=false});canvas.addEventListener('wheel',event=>{event.preventDefault();globeZoom=Math.max(.72,Math.min(1.45,globeZoom-event.deltaY*.001))},{passive:false})}
function drawGlobe(events) { const canvas=document.getElementById('intel-globe'); if(!canvas) return;bindGlobeControls(canvas); const ctx=canvas.getContext('2d'); const render=()=>{ const rect=canvas.getBoundingClientRect(), dpr=Math.min(window.devicePixelRatio||1,2), w=Math.max(1,rect.width*dpr),h=Math.max(1,rect.height*dpr); if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h} ctx.setTransform(dpr,0,0,dpr,0,0); const cw=rect.width,ch=rect.height,cx=cw/2,cy=ch/2,r=Math.min(cw,ch)*.38*globeZoom,t=Date.now()/14000; ctx.clearRect(0,0,cw,ch); const g=ctx.createRadialGradient(cx-r*.2,cy-r*.3,r*.1,cx,cy,r);g.addColorStop(0,'#123e5b');g.addColorStop(.55,'#081a30');g.addColorStop(1,'#020611');ctx.fillStyle=g;ctx.beginPath();ctx.arc(cx,cy,r,0,Math.PI*2);ctx.fill();ctx.save();ctx.beginPath();ctx.arc(cx,cy,r,0,Math.PI*2);ctx.clip();ctx.strokeStyle='rgba(0,238,255,.20)';ctx.lineWidth=1;for(let i=-4;i<=4;i++){ctx.beginPath();ctx.ellipse(cx,cy+i*r*.22,r,Math.max(8,r*(1-Math.abs(i)*.15)),0,0,Math.PI*2);ctx.stroke()} for(let i=-5;i<=5;i++){ctx.beginPath();ctx.ellipse(cx+i*r*.19,cy,Math.max(6,r*(1-Math.abs(i)*.12)),r,0,0,Math.PI*2);ctx.stroke()} events.forEach((e,index)=>{const lon=((e.longitude||0)+t*25+globeRotation)%360-180,lat=e.latitude||0,x=cx+(lon/180)*r,y=cy-(lat/90)*r*.78; if(Math.abs(x-cx)>r*.96)return;ctx.fillStyle=e.severity==='high'?'#ff4d79':'#00efff';ctx.beginPath();ctx.arc(x,y,4+Math.sin(t+index)*1.5,0,Math.PI*2);ctx.fill()});ctx.restore(); animationFrame=requestAnimationFrame(render)}; cancelAnimationFrame(animationFrame); render(); }
function renderEvents(events) { const target=document.getElementById('intel-events'); if(!target)return; target.replaceChildren(); if(!events.length){text(target,'Noch keine Beobachtungen.');return} events.slice(0,12).forEach(e=>{const prov = e.provenance || (e.domain?'derived-event':'raw-obs'); const item=row(e.title||e.RawText||'obs',`${prov} · ${e.source||e.SourceID||''} · ${e.confidence||e.Confidence||'?'}%`, (e.status||e.Severity||'UNVERIFIED').toUpperCase() ); target.append(item)});drawGlobe(events); }
function renderSources(sources) { const target=document.getElementById('intel-sources'); if(!target)return; target.replaceChildren(); sources.forEach(source=>{const name=source.name||source.Name||source.id||source.ID||'source';const meta=`${source.source_type||source.category||'rss'} · trust ${source.trust_tier!=null?source.trust_tier:(source.TrustTier!=null?source.TrustTier:'?')} · ${source.availability_status||source.freshness||'ok'}`;const item=row(name,meta,source.last_error?'DEGRADED':'UNIFIED');const sid=source.id||source.ID;if(sid)item.addEventListener('click',async()=>{item.disabled=true;try{await request(`sources/${encodeURIComponent(sid)}/collect`,{method:'POST'});await refreshIntelligence()}catch(error){/* shared model sources may not support collect */}finally{item.disabled=false}});target.append(item)}) }
function renderCorrelations(correlations){const target=document.getElementById('intel-correlations');if(!target)return;target.replaceChildren();if(!correlations.length){text(target,'Keine belastbaren Cross-Stream-Signale.');return}correlations.slice(0,8).forEach(c=>target.append(row(c.label,`${c.reason} · ${c.event_ids.length} Observations`,`${c.strength}%`)))}
function renderAlerts(alerts){const target=document.getElementById('intel-alerts');if(!target)return;target.replaceChildren();if(!alerts.length){text(target,'Keine Schwellenwert-Alerts.');return}alerts.slice(0,8).forEach(a=>{const title=a.title||a.reason||a.Reason||'Alert';const reason=a.reason||a.Reason||a.region||a.Region||'';const sev=(a.severity||a.Severity||'?')+'';const conf=a.confidence||a.Confidence||0;const item=row(String(title),String(reason),`${String(sev).toUpperCase()} · ${conf}%`);target.append(item)})}
function renderCases(cases) { const target=document.getElementById('intel-cases'); if(!target)return; target.replaceChildren(); if(!cases.length){text(target,'Noch keine Cases.');return} cases.forEach(c=>{const item=row(c.title,`${c.purpose} · ${c.evidence.length} Evidenzen`,c.status.toUpperCase());item.addEventListener('click',()=>{selectedCaseId=c.id;renderCaseDetail(c)});target.append(item)}); const active=cases.find(c=>c.id===selectedCaseId); if(active)renderCaseDetail(active); }
function renderCaseDetail(c) {const target=document.getElementById('intel-case-detail');if(!target)return; target.replaceChildren(); const h=document.createElement('h4');text(h,c.title);const p=document.createElement('p');text(p,`Zweck: ${c.purpose} · ${c.classification} · erstellt ${new Date(c.created_at).toLocaleString()}`); const summary=document.createElement('div');summary.className='intel-case-stats';text(summary,`${c.evidence.length} EVIDENZEN  ·  ${c.entities.length} ENTITÄTEN  ·  ${c.relations.length} BEZIEHUNGEN`);const privacy=document.createElement('div');privacy.className='intel-privacy-gate';text(privacy,'RE-ID GATE · NOT ELIGIBLE · PERSON-ENTITÄTEN SIND NUR CASE-HMAC-ALIASE');const timeline=document.createElement('div');timeline.className='intel-evidence';const created=document.createElement('div');text(created,`TIMELINE · CASE OPENED · ${new Date(c.created_at).toLocaleString()}`);timeline.append(created);if(!c.evidence.length){const empty=document.createElement('div');text(empty,'Noch keine versiegelte Evidenz.');timeline.append(empty)}c.evidence.slice().sort((a,b)=>new Date(a.collected_at)-new Date(b.collected_at)).forEach(e=>{const line=document.createElement('div');text(line,`SEALED · ${e.source} · ${new Date(e.collected_at).toLocaleString()} · ${e.validation_status.toUpperCase()} · SHA-256 ${e.sha256.slice(0,20)}…`);timeline.append(line)});const graph=document.createElement('div');graph.className='intel-graph';c.entities.forEach(entity=>{const node=document.createElement('span');text(node,`${entity.kind.toUpperCase()} · ${entity.label} (${entity.confidence}%)`);graph.append(node)});if(!c.entities.length)text(graph,'Keine Case-Entitäten. Aethel darf nur belegte Entitäten hinzufügen.');target.append(h,p,summary,privacy,timeline,graph);}
export async function refreshIntelligence() { try {const [status,events,cases,sources,correlations,alerts,risks]=await Promise.all([request('status'),request('events'),request('cases'),request('sources'),request('correlations'),request('alerts'),request('risks').catch(()=> ({}))]);const statusEl=document.getElementById('intel-status');const mode = status.mode || 'unified'; if(statusEl)text(statusEl,`${mode.toUpperCase()} · OBS ${status.observations||status.events||0} · RISKS ${Object.keys((risks&&risks.risks)||{}).length} · ALERTS ${(alerts.alerts||[]).length}`);renderEvents(events.events||[]);renderCases(cases.cases||[]);renderSources(sources.sources||[]);renderCorrelations(correlations.correlations||[]);renderAlerts(alerts.alerts||[]); renderRisks(risks.risks||{}); } catch(error){const statusEl=document.getElementById('intel-status');if(statusEl)text(statusEl,`CORE OFFLINE · ${error.message}`)} }
function renderRisks(risksMap){ const t=document.getElementById('intel-risks'); if(!t) return; t.replaceChildren(); const entries=Object.entries(risksMap||{}); if(!entries.length){ text(t,'No risk scores yet. Ingest geo events.');return;} entries.slice(0,6).forEach(([id,rs])=>{ const el=document.createElement('div'); el.className='intel-risk'; el.innerHTML=`<strong>${id}</strong> <span>${(rs.overall_risk||rs.OverallRisk||0).toFixed(0)}% ${rs.trend||''}</span>`; el.title='Click for explain'; el.onclick=async()=>{try{const ex=await request('explain/'+encodeURIComponent(id)); alert(ex.explanation||JSON.stringify(rs));}catch(e){alert('Explain: '+e.message)}}; t.append(el);}); }
function bindBriefing(){if(briefingBound)return;const briefing=document.getElementById('intel-briefing');if(!briefing)return;briefingBound=true;briefing.addEventListener('click',async()=>{try{const result=await request('briefing');const blob=new Blob([result.briefing],{type:'text/markdown'});const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download='aethel-global-watch-briefing.md';link.click();URL.revokeObjectURL(url)}catch(error){alert(error.message)}})}
queueMicrotask(bindBriefing);
export function setupIntelligenceUI(){const form=document.getElementById('intel-event-form');if(form)form.addEventListener('submit',async event=>{event.preventDefault();try{await request('events',{method:'POST',body:JSON.stringify({title:document.getElementById('intel-event-title').value,source:document.getElementById('intel-event-source').value,latitude:Number(document.getElementById('intel-event-lat').value)||0,longitude:Number(document.getElementById('intel-event-lon').value)||0,confidence:50,severity:'medium'})});form.reset();await refreshIntelligence()}catch(error){alert(error.message)}});const button=document.getElementById('intel-new-case');if(button)button.addEventListener('click',async()=>{const title=prompt('Case-Titel');const purpose=prompt('Zweck / legitimes Analyseziel');if(!title||!purpose)return;try{await request('cases',{method:'POST',body:JSON.stringify({title,purpose})});await refreshIntelligence()}catch(error){alert(error.message)}});const report=document.getElementById('intel-case-report');if(report)report.addEventListener('click',async()=>{if(!selectedCaseId){alert('Bitte zuerst einen Case auswählen.');return}try{const result=await request(`cases/${encodeURIComponent(selectedCaseId)}/report`);const blob=new Blob([result.report],{type:'text/markdown'});const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download=`aethel-${selectedCaseId}-report.md`;link.click();URL.revokeObjectURL(url)}catch(error){alert(error.message)}});if(!intelligenceStream&&typeof EventSource!=='undefined'){intelligenceStream=new EventSource('/v1/intelligence/stream');intelligenceStream.addEventListener('intelligence',()=>{void refreshIntelligence()});intelligenceStream.onerror=()=>{/* browser retries this local stream automatically */}}}
